CREATE INDEX flights_departure_airport_btree ON flights (departure_airport);
CREATE INDEX flights_arrival_airport_btree ON flights (arrival_airport);
CREATE INDEX flights_aircraft_code_hash ON flights USING hash (aircraft_code);
CREATE INDEX flights_departure_airport_scheduled_departure_btree ON flights (departure_airport, scheduled_departure);
CREATE INDEX flights_departure_arrival_btree ON flights (departure_airport, arrival_airport);
CREATE INDEX flights_departure_btree ON flights (scheduled_departure);
CREATE INDEX flights_departure_airport_scheduled_departure_flight_no ON flights (departure_airport, scheduled_departure, flight_no);
CREATE INDEX bookings_book_ref_hash ON bookings USING HASH (book_ref);
CREATE INDEX ticket_flights_flight_id_hash ON ticket_flights USING hash (flight_id);
CREATE INDEX boarding_passes_ticket_flight_seat_btree ON boarding_passes (ticket_no, flight_id, seat_no);
CREATE INDEX tickets_passenger_name_adelina_covering ON tickets (passenger_name, ticket_no, passenger_id) WHERE passenger_name = 'ADELINA IVANOVA';
CREATE INDEX idx_ticket_flights_fare_flight_covering ON ticket_flights (fare_conditions, flight_id, amount);
CREATE INDEX idx_seats_aircraft_fare_covering ON seats (aircraft_code, fare_conditions, seat_no);
CREATE INDEX idx_flights_departure_arrival_status ON flights (departure_airport, arrival_airport, status, scheduled_departure) WHERE status != 'Cancelled';
CREATE INDEX idx_ticket_flights_ticket_flight_amount ON ticket_flights (ticket_no, flight_id, amount);
CREATE INDEX idx_flights_aircraft_actual_range ON flights (aircraft_code, actual_departure) WHERE actual_departure BETWEEN '2012-01-01' AND '2017-12-31';
CREATE INDEX idx_boarding_passes_flight_seat_covering ON boarding_passes (flight_id, seat_no, ticket_no);
CREATE INDEX idx_tickets_book_ref_covering ON tickets (book_ref, ticket_no, passenger_name);
CREATE INDEX idx_flights_departure_arrival_airport_covering ON flights (departure_airport, arrival_airport, flight_id, aircraft_code);
CREATE INDEX idx_aircrafts_model_english ON aircrafts_data ((model->>'english'), aircraft_code);
CREATE INDEX idx_airports_city_english ON airports_data ((city->>'english'), airport_code);
CREATE INDEX idx_q5_flights_aircraft_actual_times ON flights (aircraft_code, actual_arrival, scheduled_departure, flight_id);
CREATE INDEX idx_q5_ticket_flights_flight_id_covering ON ticket_flights (flight_id) INCLUDE (amount);
CREATE INDEX ticket_flights_ticket_no_hash ON ticket_flights USING HASH (ticket_no);
CREATE INDEX boarding_passes_ticket_no_hash ON boarding_passes USING HASH (ticket_no);
CREATE INDEX boarding_passes_flight_id_hash ON boarding_passes USING HASH (flight_id);
CREATE INDEX seats_aircraft_code_hash ON seats USING HASH (aircraft_code);
CREATE INDEX seats_seat_no_hash ON seats USING HASH (seat_no);
CREATE INDEX bookings_pk_hash ON bookings USING HASH (book_ref);
CREATE INDEX airports_data_pk_hash ON airports_data USING HASH (airport_code);
CREATE INDEX tickets_pk_hash ON tickets USING HASH (ticket_no);
CREATE INDEX flights_pk_hash ON flights USING HASH (flight_id);
CREATE INDEX aircrafts_data_pk_hash ON aircrafts_data USING HASH (aircraft_code);
CREATE INDEX flights_aircraft_code_btree ON flights USING btree (aircraft_code);
CREATE INDEX bookings_book_ref_btree ON bookings USING btree (book_ref);
CREATE INDEX ticket_flights_flight_id_btree ON ticket_flights USING btree (flight_id);
CREATE INDEX ticket_flights_ticket_no_btree ON ticket_flights USING btree (ticket_no);
CREATE INDEX boarding_passes_ticket_no_btree ON boarding_passes USING btree (ticket_no);
CREATE INDEX boarding_passes_flight_id_btree ON boarding_passes USING btree (flight_id);
CREATE INDEX seats_aircraft_code_btree ON seats USING btree (aircraft_code);
CREATE INDEX seats_seat_no_btree ON seats USING btree (seat_no);
CREATE INDEX bookings_pk_btree ON bookings USING btree (book_ref);
CREATE INDEX airports_data_pk_btree ON airports_data USING btree (airport_code);
CREATE INDEX tickets_pk_btree ON tickets USING btree (ticket_no);
CREATE INDEX flights_pk_btree ON flights USING btree (flight_id);
CREATE INDEX aircrafts_data_pk_btree ON aircrafts_data USING btree (aircraft_code);
